project:
  type: website
  output-dir: docs

website:
  twitter-card: true
  title: "Structural Bioinformatics 2022-23"
  sidebar:
    style: "docked"
    tools:
      - icon: twitter
        href: https://twitter.com/mredrejo
      - icon: envelope-paper
        href: mailto:modesto.redrejo@uam.es
      - icon: github
        href: https://github.com/strBio/strbio2022_23
    search: true
    contents:
      - index.qmd
      - section: "Basics"
        contents:
          - intro.qmd
          - ddbb.qmd
          - pdb.qmd
      - section: "Modeling"
        contents:
          - homology.qmd
          - ai.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    cover-image: pics/cover.png
  pdf:
    documentclass: scrbook
    cover-image: pics/cover.png



