---
title: "Working with protein structures"
author: "Modesto Redrejo Rodríguez"
date: "`r Sys.Date()`"
toc: true 
toc_float: true
format:
  html:
    theme: simplex
    toc: true
    toc-location: right
    toc-depth: 4
    number-sections: false
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true
bibliography: references.bib
editor_options: 
  markdown: 
    wrap: 80
---

```{r wrap-hook, include=FALSE}
#Markdown options
library(knitr)
library(formatR)
opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE,fig.cap = "", fig.path = "Plot")


#Determine the output format of the document
outputFormat   = opts_knit$get("rmarkdown.pandoc.to")


```

## Protein structure display and the actual protein structure

:::{.callout-caution}
## Warning for future structural biologists
:::

[![Ceci n'est pas une proteine. Source:
https://swissmodel.expasy.org/static/course/files/PartIII_quality_assesment.pdf](pics/magritte.png "Ceci n'est pas une proteine"){.figure}](https://swissmodel.expasy.org/static/course/files/PartIII_quality_assesment.pdf)

The surrealist Belgian painter René Magritte created a collection of
surrealistic paintings entitled [***La trahison des images***
(1928--1929)](https://en.wikipedia.org/wiki/The_Treachery_of_Images "Magritte").
The most renowned of those paintings show a smoking pipe and the following
caption underneath: *"Ceci n'est pas une pipe"* (This is not a pipe). Yes,
indeed! It is actually the painting of a pipe.

Similarly, a picture of a protein, or a PDB file with the coordinates of a
protein structure, is not a protein. It is a representation of ONE structure.
Even experimentally determined structures have two main limitations that we
should always keep in mind: (1) they are a fixed structure whereas proteins *in
vivo* are flexible and dynamic and (2) they are subjected to experimental error
and they often contain regions of low reliability. Moreover, even experimentally
obtained macromolecular structures are to some degree models, with a variable
ratio between experimental data and computational prediction to match the
experimental data (X-ray diffraction, cryo-EM density maps, NMR, SAXS, FRET...)
with previously known structures or prediction models. That does not mean that
protein structures are useless, they can be very useful, but we must be aware of
the limitations as well as the applications.

# Experimentally obtained structures

# Protein structure files formats

# Biological macromolecules display applications


--------------------------------------------------------------------------------

# References
